# Prometheus конфигурация для мониторинга системы поиска
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Node.js приложение
  - job_name: 'prompthub-app'
    static_configs:
      - targets: ['localhost:3000']
    metrics_path: '/api/metrics'
    scrape_interval: 10s

  # Системные метрики
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']

  # База данных
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['localhost:9187']

  # Nginx
  - job_name: 'nginx-exporter'
    static_configs:
      - targets: ['localhost:9113']
